Resources:
  LangChainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: langchain # name of the table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id # partition key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
